# Generated by Django 5.1.5 on 2025-02-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=30)),
                ('item_type', models.CharField(max_length=30)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_availability', models.IntegerField()),
            ],
        ),
    ]
