# Generated by Django 5.1.5 on 2025-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_img',
            field=models.ImageField(null=True, upload_to='item_imgs/'),
        ),
    ]
