# Generated by Django 5.1.5 on 2025-02-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='username',
            field=models.TextField(default=None, max_length=30, null=True),
        ),
    ]
