# Generated by Django 5.1.5 on 2025-02-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_user_profile_data_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_data',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
