# Generated by Django 5.1.5 on 2025-02-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_user_profile_data_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_data',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
